# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de565139c9ce649fc3266e644609e785328ccacdb3e849dd9dceda1b00d2856b9c4257a1d04ac9ae2ac5c78cdd20aaa14f19babaa3443c7b483771d0824415c8

test:
  secret_key_base: 373b855b8a64a49ffa4a18fdb932e1fe10fc0d2785dd07f3d40b103f0c821f845388d077ec8f799c970df3a00ca7a8e75fc71d06db5010c4c65147364d69de34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
